### ISSUE TITLE
Conflict with fedora openh264 repository

### ISSUE THREAD

**Issue by HeikoAdams** [muchpack/gstreamer1-plugins-bad-freeworld#1]
The package gstreamer1-plugins-bad-freeworld conflicts with gstreamer1-plugin-openh264 from fedora openh264 repository:

> file /usr/lib64/gstreamer-1.0/libgstopenh264.so from install of gstreamer1-plugins-bad-freeworld-1.8.1-1.fc24.x86_64 conflicts with file from package gstreamer1-plugin-openh264-1.6.1-2.fc24.x86_64

**Comment by paulcarroty** [comment]
[Fixed](https://github.com/UnitedRPMs/openh264/issues/1#issuecomment-223740307).

**Comment by kuboosoft** [comment]
I can't see a "gstreamer1-plugin-openh264" in official repositories... 
I made the rpm on Tue Apr 19 2016, gstreamer made changes replacing x264 by h264; If Fedora project made fool changes without read or check if exist work made by third party projects, is a problem...
solution... add 

> "Provides: gstreamer1-plugin-openh264 = %{version}-%{release}"

**Comment by paulcarroty** [comment]
@kuboosoft please don't reopen **ALL issues**, the one is enough.

> I can't see a "gstreamer1-plugin-openh264" in official repositories... 

https://fedoraproject.org/wiki/OpenH264, will be enabled by default after F24 release.

> `"Provides: gstreamer1-plugin-openh264 = %{version}-%{release}"`

No, we don't need the codec that supports only H264 baseline profile and can't play Youtube in 720p. If users want - they can install it from official repository.

**Comment by paulcarroty** [comment]
Conflict is ended; we'll probably need to add the x264 depends.

**Comment by kuboosoft** [comment]
Isn't necessary add x264 because It is provided by gstreamer1-plugins-ugly; man! you need read the structure of each package; I will upload the changes to gstreamer1-plugins-bad-freeworld, but first I need update openh264.  gstreamer1-plugin-openh264 needs the same gstreamer1-plugins-bad-freeworld, solution "make a subpackage": Any Change drastic in gstreamer is necessary speak with the team... :)

**Comment by paulcarroty** [comment]
> but first I need update openh264

openh264 was deleted from repository.

> Any Change drastic in gstreamer is necessary speak with the team... :)

OK, let's vote. I protest against openh264 in our repo because this technology is not fully and available in official repo. @sergiomb2?

**Comment by sergiomb2** [comment]
> No, we don't need the codec that supports only H264 baseline profile and can't play Youtube in 720p. If users want - they can install it from official repository.

Hum , https://fedoraproject.org/wiki/OpenH264 says: does not enable generic H.264 playback, only WebRTC (see Mozilla bug 1057646). 
That was my question, fedora OpenH264  **does not enable generic H.264 playback**, I can't vote because I don't know all aspects of the problem , but by default, I support  kuboosoft :smile: 
ah anyway , I don't know if it match but :
libde265 is an open source implementation of the H.265 video codec.
https://bugzilla.rpmfusion.org/show_bug.cgi?id=3335

**Comment by sergiomb2** [comment]
> but first I need update openh264

openh264 was deleted from repository by issue https://github.com/UnitedRPMs/openh264/issues/1 , @kuboosoft do you want readd openh264 ? , what we should do about fedora H.264 playback, only for WebRTC ?

**Comment by kuboosoft** [comment]
@sergiomb2 H.264 is provided by gstreamer1-ugly

**Comment by sergiomb2** [comment]
http://unitedrpms.sourceforge.net/srpm/repoview/gstreamer1-plugins-ugly.html was not modified ... , now I don't understand do we need openh264 from unitedrpms or not ? 
http://unitedrpms.sourceforge.net/srpm/repoview/gstreamer1-plugins-bad-freeworld.html
ah Paul disable openh264 , if we try reenabled it, could use openh264  from fedora ? it builds ?

**Comment by paulcarroty** [comment]
> http://unitedrpms.sourceforge.net/srpm/repoview/gstreamer1-plugins-ugly.html was not modified

Hmm, bad script? Maybe need to add a delete old HTML before add new packages.

> now I don't understand do we need openh264 from unitedrpms

@kuboosoft need it and I can't understand why.

**Comment by sergiomb2** [comment]
> >  http://unitedrpms.sourceforge.net/srpm/repoview/gstreamer1-plugins-ugly.html was not modified
> 
> Hmm, bad script? Maybe need to add a delete old HTML before add new packages.

I update sync repos script to sourceforge and is the lastest version of gstreamer1-plugins-ugly on srpm , maybe not the latest x86_64 ... , but now we have repoviews in sourceforge updated

**Comment by paulcarroty** [comment]
gstreamer1-plugins-bad-freeworld, not gstreamer1-plugins-ugly.

**Comment by sergiomb2** [comment]
that is the point @kuboosoft  said H.264 is provided by gstreamer1-ugly , not me

**Comment by paulcarroty** [comment]
> Isn't necessary add x264 because It is provided by gstreamer1-plugins-ugly

He talk because I would include x264 to gstreamer1-plugins-bad-freeworld :smile:

**Comment by kuboosoft** [comment]
@sergiomb2 
gstreamer1-plugins-ugly provides:

`%{_libdir}/gstreamer-1.0/libgstx264.so`

all fine,here no problem..

**The real problem**
gstreamer1-plugins-bad-freeworld 
I don't need openh264; the problem is the openh264 support for gstreamer will be affected the gstreamer1-plugins-bad-freeworld in the future; It requires the same version (gstreamer1-plugins-bad-freeworld); I don't see a clear status for gstreamer1-plugin-openh264 because; is a legal issue, if isn't clear why no rpmfusion provides it...

I searched all information relationated with openh264.  I found this crazy  rpm includes  bundled 'build requires' as a plugin for Firefox and the same gstreamer (cut) excluding others parts from gstreamer1-plugins-bad-freeworld...
https://codecs.fedoraproject.org/openh264/24/source/
 https://phab.qadevel.cloud.fedoraproject.org/T803
http://koji.fedoraproject.org/koji/buildinfo?buildID=758341
https://fedoraproject.org/wiki/OpenH264
https://ausil.us/wordpress/?p=126

Well; the comits for openh264 above doesn't exist, In [git](https://github.com/cisco/openh264/issues/2437) Isn't visible a [release official ](https://github.com/cisco/openh264/releases)1.5.2/1.5.3 version :/

I made the changes to our [openh264](https://github.com/UnitedRPMs/openh264); It provides important tools; also [gstreamer1-plugins-bad-freeworld](https://github.com/FedoraUnited/gstreamer1-plugins-bad-freeworld.git) You can test it @paulcarroty @sergiomb2 and compare with http://koji.fedoraproject.org/koji/buildinfo?buildID=758341

Then, the user if enables [this repository](https://fedoraproject.org/wiki/OpenH264); can update without problem...
